//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerDemo {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Display N18 module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_N18 display_N18;
        
        /// <summary>The XBee module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.XBee xBee;
        
        /// <summary>The TemperatureHumidity module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;
        
        /// <summary>The Breakout TB10 module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Breakout_TB10 breakout_TB10;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerberus Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerberus)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerberus();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.display_N18 = new GTM.GHIElectronics.Display_N18(5);
            this.xBee = new GTM.GHIElectronics.XBee(6);
            this.temperatureHumidity = new GTM.Seeed.TemperatureHumidity(7);
            this.breakout_TB10 = new GTM.GHIElectronics.Breakout_TB10(4);
        }
    }
}
